# Site settings
title:       "Template title"
email:       "templateemail@email.com"
author:      "Template Author"
description: "Templatedescriprion"
url:         "http://example.com"

# Authors
authors:
  author:
    name: "Author name"
    display_name: "author display name"
    email: author email
    twitter: author_twitter
    active: ""

# Google analytics
google_analytics: 

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  true



# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons

show_social_icons: true
github_username: 
stackoverflow_id:
twitter_username: 

google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     10
sass:
  compressed: true

